services:
    - docker:dind

stages:
    - build-image

before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

variables:
    REGISTRY: registry.gitlab.com/sirmonin/barside
    IMAGE_NAME: $REGISTRY:latest

master-build:
    image: docker:latest
    stage: build-image
    script:
        - docker build -t $IMAGE_NAME .
        - docker push $IMAGE_NAME
    only:
        - master
